### PR TITLE
fix - outline button hover effects

### LINKED ISSUE #3: Fix outline buttons hover effect
Instead of this:
kép

I would go with this:
kép

And instead of this:
kép

This would work better:
kép

### PR DESCRIPTION
**Pull request by polgarj**

### CODE REVIEW

**Comment by amandewatnitrr** [comment]
Can you share me an Image of localhost how it looks after the merge.

**Comment by polgarj** [comment]
Of course. Here it is:

kép

**Comment by amandewatnitrr** [comment]
I suggest you make the same pull-request on our hacktoberfest branch and we will merge it there.

**Comment by amandewatnitrr** [comment]
Great Work!! Really Love it

**Pull request merged**
