### PR TITLE
added animation and improved the ui

### PR DESCRIPTION
**Pull request by aryan2621**
](https://user-images.githubusercontent.com/69208178/136372518-ca7ca568-371b-489a-9ad0-02baf7c7d1e3.png)
Screenshot (206)
Screenshot (205)
)

### CODE REVIEW

**Comment by aryan2621** [comment]
Apologitic for being late........want some more info about the code specially css.

**Comment by amandewatnitrr** [comment]
Is the Discord animation blinking??

**Comment by aryan2621** [comment]
> Is the Discord animation blinkin

> Is the Discord animation blinking??

Which part.... Show that with screenshot

**Comment by amandewatnitrr** [comment]
I was asking??

**Comment by amandewatnitrr** [comment]
Anyway, I checked it's great. merging it.

**Comment by aryan2621** [comment]
> Anyway, I checked it's great. merging it.

Thanks a lot. I m thank full that you liked the work I did.

**Comment by aryan2621** [comment]
Will finish that front page. Till tomorrow. May be some problem of responsiveness, due to conflicting CSS.

**Pull request merged**
