### PR TITLE
Footer UI Update

### LINKED ISSUE #9: Footer UI can be improved.

### PR DESCRIPTION
**Pull request by sahilsaini1107**

### CODE REVIEW

**Comment by amandewatnitrr** [comment]
Share the Localhost Screenshot showing what changes have occured on website.

**Comment by sahilsaini1107** [comment]
ya sure

**Comment by sahilsaini1107** [comment]
BEFORE..


Screenshot from 2021-10-01 22-34-35

**Comment by sahilsaini1107** [comment]
AFTER..


Screenshot from 2021-10-01 22-33-50

**Pull request merged**
